<?php

namespace App\Http\Controllers;


use App\Notifications\SpecialityNotification;
use App\Notifier\Channel;
use App\Notifier\Dsn;
use App\Notifier\Recipient\Recipient;
use Illuminate\Support\Facades\Notification;

class WebhookController extends Controller
{
    public function __call($method, $parameters)
    {
        parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        // dsn = 'type://channel@account'

        // dsn = 'sms://aliyun@default'
        // dsn = 'sms://aliyun@ssl100'
        // dsn = 'chat://wecom@cmzz'
        // dsn = 'chat://wechat_mp@default'


        $this->sendByChannel();
    }

    public function sendByChannel()
    {
        // 参数
        $params = [
            'dsn' => 'email://netease@ssl100',
            'to' => [
                'name' => 'test',
                'to' => 'me19@qq.com',
            ],
            'from' => [
                'name' => '',
                'address' => '',
            ],
            'data' => [
                'content' => '',    //  文本内容，用于邮件（支持html）、境外短信
                'tmpl_id' => '', // 模板id 用于国内sms / email
                'params' => '', // 模板参数 用于国内sms / email
                'sign' => '', // 签名 用于国内sms
                'attachment' => [

                ],  // 附件 用于邮件

            ],
        ];

        $recipient = new Recipient($params['to']);


        $dsn = new Dsn($params['dsn']);
        $channel = new Channel($dsn);
        $n = new SpecialityNotification($channel);
        $n->from($params['from']);
        $n->content($params['data']);

        Notification::route('notifier', $recipient)->notify($n);
    }

    public function publishToTopic()
    {

    }
}
